# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_factor"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "string manipulation"
categories = ["factor"]
keywords = ["fortran", "factor"]
homepage = "https://github.com/urbanjost/M_factor.git"

[build]
#module-naming = true

# demo programs
[install]
library=true

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_factor.f90"
[test.dependencies]
M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }

[dependencies]
M_kracken      = { git = "https://github.com/urbanjost/M_kracken.git" }
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
